/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void forwardButton1_click1(GImageButton source, GEvent event) { //_CODE_:forwardButton:958447:
  println("forwardButton - GImageButton >> GEvent." + event + " @ " + millis());
  myPort.write('w');
} //_CODE_:forwardButton:958447:

public void backButton_click1(GImageButton source, GEvent event) { //_CODE_:backButton:987220:
  println("backButton - GImageButton >> GEvent." + event + " @ " + millis());
  myPort.write('s');
} //_CODE_:backButton:987220:

public void leftButton_click1(GImageButton source, GEvent event) { //_CODE_:leftButton:605726:
  println("leftButton - GImageButton >> GEvent." + event + " @ " + millis());
  myPort.write('a');
} //_CODE_:leftButton:605726:

public void rightButton_click1(GImageButton source, GEvent event) { //_CODE_:rightButton:285485:
  println("rightButton - GImageButton >> GEvent." + event + " @ " + millis());
  myPort.write('d');
} //_CODE_:rightButton:285485:

public void stopButton_click1(GImageButton source, GEvent event) { //_CODE_:stopButton:680797:
  println("stopButton - GImageButton >> GEvent." + event + " @ " + millis());
    myPort.write('k');
} //_CODE_:stopButton:680797:

public void logArea_change1(GTextArea source, GEvent event) { //_CODE_:logArea:902338:
  println("logArea - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:logArea:902338:

public void autoButton_click1(GImageButton source, GEvent event) { //_CODE_:autoButton:670413:
  println("autoButton - GImageButton >> GEvent." + event + " @ " + millis());
    myPort.write('y');
} //_CODE_:autoButton:670413:

public void caliberateButton_click1(GImageButton source, GEvent event) { //_CODE_:CaliberateButton:212735:
  println("CaliberateButton - GImageButton >> GEvent." + event + " @ " + millis());
    myPort.write('h');
} //_CODE_:CaliberateButton:212735:

public void searchButton_click1(GImageButton source, GEvent event) { //_CODE_:searchButton:383464:
  println("searchButton - GImageButton >> GEvent." + event + " @ " + millis());
    myPort.write('z');
} //_CODE_:searchButton:383464:

public void endButton_click1(GImageButton source, GEvent event) { //_CODE_:endButton:929806:
  println("endButton - GImageButton >> GEvent." + event + " @ " + millis());
    myPort.write('e');
} //_CODE_:endButton:929806:

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:imgButton1:440702:
  println("imgButton1 - GImageButton >> GEvent." + event + " @ " + millis());
    myPort.write('t');
} //_CODE_:imgButton1:440702:

public void imgButton2_click1(GImageButton source, GEvent event) { //_CODE_:imgButton2:238360:
  println("imgButton2 - GImageButton >> GEvent." + event + " @ " + millis());
    myPort.write('r');
} //_CODE_:imgButton2:238360:

public void imgButton3_click1(GImageButton source, GEvent event) { //_CODE_:stopRoomButton3:333808:
  println("stopRoomButton3 - GImageButton >> GEvent." + event + " @ " + millis());
    myPort.write('b');
} //_CODE_:stopRoomButton3:333808:

public void completeButton3_click2(GImageButton source, GEvent event) { //_CODE_:completeButton3:401804:
  println("completeButton3 - GImageButton >> GEvent." + event + " @ " + millis());
    myPort.write('c');
} //_CODE_:completeButton3:401804:

public void junctionButton3_click3(GImageButton source, GEvent event) { //_CODE_:junctionButton3:402041:
  println("junctionButton3 - GImageButton >> GEvent." + event + " @ " + millis());
    myPort.write('v');
} //_CODE_:junctionButton3:402041:

public void hornButton3_click2(GImageButton source, GEvent event) { //_CODE_:hornButton3:848987:
  println("hornButton3 - GImageButton >> GEvent." + event + " @ " + millis());
    myPort.write('m');
} //_CODE_:hornButton3:848987:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  forwardButton = new GImageButton(this, 484, 476, 50, 50, new String[] { "button-29139_960_720.png", "button-29139_960_720.png", "button-29139_960_720.png" } );
  forwardButton.addEventHandler(this, "forwardButton1_click1");
  backButton = new GImageButton(this, 482, 612, 50, 50, new String[] { "arrow-29261_960_720.png", "arrow-29261_960_720.png", "arrow-29261_960_720.png" } );
  backButton.addEventHandler(this, "backButton_click1");
  leftButton = new GImageButton(this, 418, 544, 50, 50, new String[] { "left-28998_960_720.png", "left-28998_960_720.png", "left-28998_960_720.png" } );
  leftButton.addEventHandler(this, "leftButton_click1");
  rightButton = new GImageButton(this, 548, 544, 50, 50, new String[] { "arrow-30330_960_720.png", "arrow-30330_960_720.png", "arrow-30330_960_720.png" } );
  rightButton.addEventHandler(this, "rightButton_click1");
  stopButton = new GImageButton(this, 484, 544, 50, 50, new String[] { "stop-button-clipart-1.jpg.png", "stop-button-clipart-1.jpg.png", "stop-button-clipart-1.jpg.png" } );
  stopButton.addEventHandler(this, "stopButton_click1");
  logArea = new GTextArea(this, 52, 43, 339, 221, G4P.SCROLLBARS_VERTICAL_ONLY | G4P.SCROLLBARS_AUTOHIDE);
  logArea.setOpaque(true);
  logArea.addEventHandler(this, "logArea_change1");
  autoButton = new GImageButton(this, 51, 280, 84, 80, new String[] { "autoButton.png", "autoButton.png", "autoButton.png" } );
  autoButton.addEventHandler(this, "autoButton_click1");
  CaliberateButton = new GImageButton(this, 196, 280, 84, 80, new String[] { "caliButton.png", "caliButton.png", "caliButton.png" } );
  CaliberateButton.addEventHandler(this, "caliberateButton_click1");
  searchButton = new GImageButton(this, 51, 371, 84, 80, new String[] { "searchRoom.png", "searchRoom.png", "searchRoom.png" } );
  searchButton.addEventHandler(this, "searchButton_click1");
  endButton = new GImageButton(this, 194, 568, 84, 80, new String[] { "endButton.png", "endButton.png", "endButton.png" } );
  endButton.addEventHandler(this, "endButton_click1");
  imgButton1 = new GImageButton(this, 381, 417, 100, 100, new String[] { "rotate_ccw_cw_button-512.png", "rotate_ccw_cw_button-512.png", "rotate_ccw_cw_button-512.png" } );
  imgButton1.addEventHandler(this, "imgButton1_click1");
  imgButton2 = new GImageButton(this, 534, 417, 100, 100, new String[] { "rotate_cw_ccw_button-512.png", "rotate_cw_ccw_button-512.png", "rotate_cw_ccw_button-512.png" } );
  imgButton2.addEventHandler(this, "imgButton2_click1");
  stopRoomButton3 = new GImageButton(this, 196, 371, 84, 80, new String[] { "stopForRoom.png", "stopForRoom.png", "stopForRoom.png" } );
  stopRoomButton3.addEventHandler(this, "imgButton3_click1");
  completeButton3 = new GImageButton(this, 51, 475, 84, 80, new String[] { "buttomComplete.png", "buttomComplete.png", "buttomComplete.png" } );
  completeButton3.addEventHandler(this, "completeButton3_click2");
  junctionButton3 = new GImageButton(this, 196, 471, 84, 80, new String[] { "junctionButton.png", "junctionButton.png", "junctionButton.png" } );
  junctionButton3.addEventHandler(this, "junctionButton3_click3");
  hornButton3 = new GImageButton(this, 51, 568, 84, 80, new String[] { "horn.png", "horn.png", "horn.png" } );
  hornButton3.addEventHandler(this, "hornButton3_click2");
}

// Variable declarations 
// autogenerated do not edit
GImageButton forwardButton; 
GImageButton backButton; 
GImageButton leftButton; 
GImageButton rightButton; 
GImageButton stopButton; 
GTextArea logArea; 
GImageButton autoButton; 
GImageButton CaliberateButton; 
GImageButton searchButton; 
GImageButton endButton; 
GImageButton imgButton1; 
GImageButton imgButton2; 
GImageButton stopRoomButton3; 
GImageButton completeButton3; 
GImageButton junctionButton3; 
GImageButton hornButton3; 
